version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=yii_db
      - MYSQL_USER=yii_user
      - MYSQL_PASSWORD=user_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-data:
